import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1784015701570 implements MigrationInterface {
    name = 'InitialSchema1784015701570'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vendors" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "contactPerson" character varying, "email" character varying, "phone" character varying, "address" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_83065ec2a2c5052786c122e95ba" UNIQUE ("name"), CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "token" character varying(255) NOT NULL, "otp_hash" character varying(255), "attempts" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP NOT NULL, "is_used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "UQ_ab673f0e63eac966762155508ee" UNIQUE ("token"), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ab673f0e63eac966762155508e" ON "password_reset_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_52ac39dd8a28730c63aeb428c9" ON "password_reset_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "slug" character varying NOT NULL, "description" character varying NOT NULL, "module" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d090ad82a0e97ce764c06c7b312" UNIQUE ("slug"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."asset_photos_condition_enum" AS ENUM('excellent', 'good', 'fair', 'poor', 'damaged')`);
        await queryRunner.query(`CREATE TABLE "asset_photos" ("id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "filename" character varying NOT NULL, "file_path" character varying NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying NOT NULL, "condition" "public"."asset_photos_condition_enum" NOT NULL DEFAULT 'good', "notes" text, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d141b644ee320a67038e64b2c76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_96db6bbbaa6f23cad26871339b6" UNIQUE ("name"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assets" ("id" SERIAL NOT NULL, "asset_tag" character varying NOT NULL, "name" character varying NOT NULL, "hostname" character varying, "category" character varying(50) NOT NULL, "brand" character varying, "brand_id" integer, "vendor" character varying, "vendor_id" integer, "received_from_vendor_date" date, "vendor_monthly_rent" numeric(10,2), "model" character varying, "serial_number" character varying, "status" character varying(50) NOT NULL DEFAULT 'available', "condition" character varying(50) NOT NULL DEFAULT 'good', "acquisition_type" character varying(20) NOT NULL DEFAULT 'purchased', "purchase_date" date, "purchase_cost" numeric(10,2), "currency" character varying(3) NOT NULL DEFAULT 'INR', "warranty_expiry" date, "warranty_start" date, "warranty_type" character varying, "po_number" character varying, "invoice_number" character varying, "cost_center" character varying, "business_owner_id" integer, "assigned_to_id" integer, "deployment_date" date, "location" character varying, "site" character varying, "building" character varying, "floor" character varying, "room_desk" character varying, "last_maintenance_date" date, "next_maintenance_date" date, "maintenance_notes" text, "maintenance_cycle_days" integer, "useful_life_years" integer NOT NULL DEFAULT '3', "salvage_value" numeric(10,2), "current_value" numeric(10,2), "disposal_date" date, "disposal_method" character varying, "disposal_notes" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_490daec7711d8e8bedd6a5a7caa" UNIQUE ("asset_tag"), CONSTRAINT "PK_da96729a8b113377cfb6a62439c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "license_renewals" ("id" SERIAL NOT NULL, "license_id" integer NOT NULL, "old_expiry_date" date, "new_expiry_date" date NOT NULL, "cost_change" numeric(10,2) NOT NULL DEFAULT '0', "remarks" text, "renewed_by" integer, "renewed_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e985690734238a0aebe70595da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "license_plans" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "product_family" character varying, "vendor_id" integer NOT NULL, "type" character varying, "category" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e45721a024d58186e03b02bca05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "licenses" ("id" SERIAL NOT NULL, "software_name" character varying NOT NULL, "vendor" character varying, "vendor_id" integer, "category" character varying NOT NULL DEFAULT 'saas_sub', "type" character varying NOT NULL DEFAULT 'user', "plan_name" character varying, "license_plan_id" integer, "product_key" character varying, "contract_id" character varying, "tenant_id" character varying, "total_seats" integer NOT NULL DEFAULT '1', "used_seats" integer NOT NULL DEFAULT '0', "cloud_mode" boolean NOT NULL DEFAULT true, "unit_price" numeric(10,2) NOT NULL DEFAULT '0', "total_cost" numeric(12,2) DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'USD', "billing_frequency" character varying NOT NULL DEFAULT 'monthly', "commitment_term" character varying, "purchase_date" date, "expiry_date" date, "next_renewal_date" date, "notice_period_days" integer NOT NULL DEFAULT '30', "renewal_status" character varying, "compliance_risk" character varying, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_da5021501ce80efa03de6f40086" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "license_assignments" ("id" SERIAL NOT NULL, "license_id" integer NOT NULL, "user_id" integer NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "notes" character varying, CONSTRAINT "PK_35aaf32efc943d97447e3bcc17e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "role_id" integer, "password_hash" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "is_verified" boolean NOT NULL DEFAULT false, "last_login" TIMESTAMP, "phone_number" character varying(20), "location" character varying(100), "token_version" integer NOT NULL DEFAULT '0', "settings" json, "is_sso_user" boolean NOT NULL DEFAULT false, "azure_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_2aa866fd1ec401cc1f4fa2efeb6" UNIQUE ("azure_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "code" character varying(5), "description" text, "isActive" boolean NOT NULL DEFAULT true, "allowedTargetTypes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_77d7eff8a7aaa05457a12b8007a" UNIQUE ("code"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."catalog_items_returnpolicy_enum" AS ENUM('returnable', 'consumable', 'assign_once')`);
        await queryRunner.query(`CREATE TYPE "public"."catalog_items_trackmode_enum" AS ENUM('serialized', 'bulk_qty')`);
        await queryRunner.query(`CREATE TABLE "catalog_items" ("id" SERIAL NOT NULL, "sku" character varying(50) NOT NULL, "name" character varying(300) NOT NULL, "description" text, "categoryId" integer, "returnPolicy" "public"."catalog_items_returnpolicy_enum" NOT NULL, "trackMode" "public"."catalog_items_trackmode_enum" NOT NULL, "unitOfMeasure" character varying(50) NOT NULL DEFAULT 'each', "reorderPoint" integer NOT NULL DEFAULT '0', "brand" character varying(100), "model" character varying(100), "imageUrl" character varying(500), "unitCost" numeric(12,2), "currency" character varying(3) NOT NULL DEFAULT 'INR', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8d43e77f403dce4074eb0f0798b" UNIQUE ("sku"), CONSTRAINT "PK_dd1c29828c10a599d894b9b6535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bf702b2d6db3ff835efd6f11e2" ON "catalog_items" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f764d91232b2eb16a79aeae76" ON "catalog_items" ("trackMode") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a3bd6068277aef05f19015871" ON "catalog_items" ("returnPolicy") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8d43e77f403dce4074eb0f0798" ON "catalog_items" ("sku") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, "address" character varying(500), "building" character varying(100), "floor" character varying(100), "room" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_227023051ab1fedef7a3b6c7e2" ON "locations" ("name") `);
        await queryRunner.query(`CREATE TABLE "stock_by_location" ("id" SERIAL NOT NULL, "catalogItemId" integer NOT NULL, "locationId" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4424ca3713423146d1e29c5ab32" UNIQUE ("catalogItemId", "locationId"), CONSTRAINT "CHK_cc512bb500d21f725c77bcf28a" CHECK ("quantity" >= 0), CONSTRAINT "PK_75305a1d2e8861f878c41cf4673" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35a43d299f796bbd64c3ffd0b5" ON "stock_by_location" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb039403817535895c40439fec" ON "stock_by_location" ("catalogItemId") `);
        await queryRunner.query(`CREATE TYPE "public"."asset_units_status_enum" AS ENUM('in_stock', 'assigned', 'in_maintenance', 'in_repair', 'lost', 'written_off', 'disposed')`);
        await queryRunner.query(`CREATE TYPE "public"."asset_units_condition_enum" AS ENUM('new', 'excellent', 'good', 'fair', 'poor', 'damaged')`);
        await queryRunner.query(`CREATE TABLE "asset_units" ("id" SERIAL NOT NULL, "assetTag" character varying(50) NOT NULL, "catalogItemId" integer NOT NULL, "serialNumber" character varying(100), "status" "public"."asset_units_status_enum" NOT NULL DEFAULT 'in_stock', "condition" "public"."asset_units_condition_enum" NOT NULL DEFAULT 'new', "locationId" integer, "purchaseDate" date, "purchaseCost" numeric(12,2), "currency" character varying(3) NOT NULL DEFAULT 'INR', "vendor" character varying(200), "warrantyExpiry" date, "usefulLifeYears" integer, "salvageValue" numeric(12,2), "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9956bc6c072603486133d691c1f" UNIQUE ("assetTag"), CONSTRAINT "PK_25fc28dd4e9ce20f2c94e90ddc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d17a33a486dca5b890f01dde69" ON "asset_units" ("catalogItemId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d387d47199986aa3f399295932" ON "asset_units" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_32f5a46a46d9f7e25f68dca948" ON "asset_units" ("serialNumber") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9956bc6c072603486133d691c1" ON "asset_units" ("assetTag") `);
        await queryRunner.query(`CREATE TABLE "departments" ("id" SERIAL NOT NULL, "name" character varying(200) NOT NULL, "description" character varying(500), "costCenter" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8681da666ad9699d568b3e9106" ON "departments" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."assignments_status_enum" AS ENUM('active', 'returned', 'partially_returned', 'overdue', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" SERIAL NOT NULL, "catalogItemId" integer NOT NULL, "assetUnitId" integer, "assigneeId" integer NOT NULL, "assignedById" integer NOT NULL, "locationId" integer, "departmentId" integer, "quantity" integer NOT NULL DEFAULT '1', "returnedQuantity" integer NOT NULL DEFAULT '0', "dueDate" TIMESTAMP, "status" "public"."assignments_status_enum" NOT NULL DEFAULT 'active', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_f5409e65a60f670e430bdf54ec" CHECK ("quantity" > 0), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ce6063ba9705d8ce937dfee002" ON "assignments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d17420638d8d432b3a20c0ea" ON "assignments" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0ccdc14bc299781045945f4ae" ON "assignments" ("assetUnitId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e324eadbd3cc72c15c27de9ba2" ON "assignments" ("catalogItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4b937c5c857e8c50ef7f292f1" ON "assignments" ("assigneeId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."return_transactions_conditiononreturn_enum" AS ENUM('new', 'excellent', 'good', 'fair', 'poor', 'damaged')`);
        await queryRunner.query(`CREATE TABLE "return_transactions" ("id" SERIAL NOT NULL, "assignmentId" integer NOT NULL, "quantity" integer NOT NULL, "conditionOnReturn" "public"."return_transactions_conditiononreturn_enum" NOT NULL DEFAULT 'good', "returnedById" integer NOT NULL, "processedById" integer NOT NULL, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "CHK_9168f0c2c93f613097791fc9f5" CHECK ("quantity" > 0), CONSTRAINT "PK_dd476a3cd97eba9b63ae0977701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b59291df6f8917de86d4d44eff" ON "return_transactions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_98f7c49dfdbead469306db6189" ON "return_transactions" ("assignmentId") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("key" character varying NOT NULL, "value" text, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1b5bc664526d375c94ce9ad43d" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "lookups" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, "label" character varying NOT NULL, "value" character varying NOT NULL, "description" character varying, "sortOrder" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_110e4351a09dc331837f1731114" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_ledger_reason_enum" AS ENUM('initial_stock', 'procurement', 'issue', 'return', 'transfer_in', 'transfer_out', 'adjustment', 'write_off', 'lost', 'disposed')`);
        await queryRunner.query(`CREATE TABLE "stock_ledger" ("id" SERIAL NOT NULL, "catalogItemId" integer NOT NULL, "locationId" integer NOT NULL, "quantityChange" integer NOT NULL, "runningBalance" integer NOT NULL, "reason" "public"."stock_ledger_reason_enum" NOT NULL, "referenceType" character varying(50), "referenceId" integer, "notes" text, "createdById" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bb04575ee2ff52f72028f669701" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7806525fee4483e4e10cca783" ON "stock_ledger" ("referenceType", "referenceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77bb476a348b79a1855957b417" ON "stock_ledger" ("reason") `);
        await queryRunner.query(`CREATE INDEX "IDX_52b319a89e98ef1a1942c94435" ON "stock_ledger" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_a67d66a61b50be403324772469" ON "stock_ledger" ("catalogItemId", "locationId") `);
        await queryRunner.query(`CREATE TYPE "public"."license_history_action_enum" AS ENUM('created', 'updated', 'assigned', 'unassigned', 'renewed', 'audited', 'seat_adjustment')`);
        await queryRunner.query(`CREATE TABLE "license_history" ("id" SERIAL NOT NULL, "license_id" integer NOT NULL, "action" "public"."license_history_action_enum" NOT NULL, "performed_by_id" integer, "assigned_to_id" integer, "notes" text, "action_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0a489ec150d3bd080e66f535da3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_categories" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_58bcb7da9b8fb06aa8a8f34aae1" UNIQUE ("name"), CONSTRAINT "PK_9903ce18e20acdba3c32c997dc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_assignments_target_type_enum" AS ENUM('PERSON', 'LOCATION')`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_assignments_status_enum" AS ENUM('assigned', 'returned', 'closed')`);
        await queryRunner.query(`CREATE TABLE "inventory_assignments" ("id" SERIAL NOT NULL, "target_type" "public"."inventory_assignments_target_type_enum" NOT NULL DEFAULT 'PERSON', "user_id" integer, "location" character varying(255), "department" character varying(100), "item_id" integer NOT NULL, "quantity" integer NOT NULL, "assignment_date" TIMESTAMP NOT NULL DEFAULT now(), "expected_return_date" TIMESTAMP, "status" "public"."inventory_assignments_status_enum" NOT NULL DEFAULT 'assigned', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f3d6607db982e2075f13d0cd529" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcf2a334e40205c646e0809886" ON "inventory_assignments" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_purchases" ("id" SERIAL NOT NULL, "vendor_name" character varying(255) NOT NULL, "invoice_number" character varying(100), "purchase_date" TIMESTAMP NOT NULL, "item_id" integer NOT NULL, "quantity" integer NOT NULL, "pack_quantity" integer, "units_per_pack" integer NOT NULL DEFAULT '1', "unit_cost" numeric(12,2) NOT NULL, "total_cost" numeric(12,2) NOT NULL, "remarks" text, "currency" character varying(10) NOT NULL DEFAULT 'USD', "invoice_attachment" character varying(500), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_e2164ffa30a08c2c4c6e52bcdb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "category_id" integer NOT NULL, "is_refundable" boolean NOT NULL DEFAULT false, "total_stock" integer NOT NULL DEFAULT '0', "available_stock" integer NOT NULL DEFAULT '0', "min_stock_level" integer NOT NULL DEFAULT '5', "units_per_pack" integer NOT NULL DEFAULT '1', "vendor" character varying(255), "supplier" character varying(255), "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transactions_type_enum" AS ENUM('IN', 'OUT', 'RETURN', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" SERIAL NOT NULL, "item_id" integer NOT NULL, "type" "public"."inventory_transactions_type_enum" NOT NULL, "quantity" integer NOT NULL, "reference_id" integer, "reference_type" character varying(50), "transaction_date" TIMESTAMP NOT NULL DEFAULT now(), "performed_by_id" integer, "notes" text, CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_073259120ddd23357a88f7cd11" ON "inventory_transactions" ("item_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_returns" ("id" SERIAL NOT NULL, "assignment_id" integer NOT NULL, "item_id" integer NOT NULL, "return_date" TIMESTAMP NOT NULL DEFAULT now(), "item_condition" character varying(100), "approved_by_id" integer, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_7e167af91b810bc3a3b5305fa3" UNIQUE ("assignment_id"), CONSTRAINT "PK_6f902d48c21495592cdc6b7eb19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_audits_status_enum" AS ENUM('in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "inventory_audits" ("id" SERIAL NOT NULL, "audit_date" TIMESTAMP NOT NULL DEFAULT now(), "auditor_id" integer NOT NULL, "status" "public"."inventory_audits_status_enum" NOT NULL DEFAULT 'in_progress', "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d7c75be5bfbcf38b0ac1c4016f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_audit_details" ("id" SERIAL NOT NULL, "audit_id" integer NOT NULL, "item_id" integer NOT NULL, "system_quantity" integer NOT NULL, "physical_quantity" integer NOT NULL, "variance" integer NOT NULL, "notes" text, CONSTRAINT "PK_04f7203f9fde07f18ec445048d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "user_id" integer, "action" character varying(50) NOT NULL, "entity_type" character varying(50), "entity_id" integer, "old_values" jsonb, "new_values" jsonb, "ip_address" character varying(50), "user_agent" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_events_action_enum" AS ENUM('issue', 'return', 'partial_return', 'transfer', 'repair_start', 'repair_end', 'lost', 'write_off', 'adjust', 'dispose', 'create', 'update', 'delete', 'login', 'approval', 'rejection')`);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" SERIAL NOT NULL, "action" "public"."audit_events_action_enum" NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" integer, "actorId" integer, "metadata" jsonb NOT NULL DEFAULT '{}', "ipAddress" character varying(50), "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f58e6602b568fd712285ea2bc" ON "audit_events" ("entityType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7f51b93a1819ea59b9df7d9855" ON "audit_events" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e76ea4cc84a0e407c5a3aeb05" ON "audit_events" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_746df228cec6a874b390563e1b" ON "audit_events" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_68d908019304f757740bc47a0a" ON "audit_events" ("action") `);
        await queryRunner.query(`CREATE TYPE "public"."asset_history_action_enum" AS ENUM('created', 'updated', 'checkout', 'checkin', 'maintenance_start', 'maintenance_end', 'disposed', 'location_change', 'depreciation')`);
        await queryRunner.query(`CREATE TABLE "asset_history" ("id" SERIAL NOT NULL, "asset_id" integer NOT NULL, "action" "public"."asset_history_action_enum" NOT NULL, "performed_by_id" integer, "assigned_to_id" integer, "location" character varying, "changes" jsonb, "notes" text, "action_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_409e5fb8b4b5b0252accb6bc435" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_photos" ADD CONSTRAINT "FK_9760c76293e0a181a0a6250b902" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_37a207d834cdfe6e294616342f7" FOREIGN KEY ("brand_id") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_a4d58da8b1bdb73a0946964e6cc" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_ec53e5ca409bb03e5f43bf23a27" FOREIGN KEY ("business_owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_6606d89e4be6895f6a4551feaad" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_renewals" ADD CONSTRAINT "FK_227c0a412f8eb5bbbe24b84f697" FOREIGN KEY ("license_id") REFERENCES "licenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_plans" ADD CONSTRAINT "FK_98ef9cd523400a3d25f8652ac5e" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licenses" ADD CONSTRAINT "FK_47ae80077d102b313d9572b14a0" FOREIGN KEY ("vendor_id") REFERENCES "vendors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "licenses" ADD CONSTRAINT "FK_f2bd0788ec18281811ed136a863" FOREIGN KEY ("license_plan_id") REFERENCES "license_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_assignments" ADD CONSTRAINT "FK_24b5eaffadc6997358d3bd5f379" FOREIGN KEY ("license_id") REFERENCES "licenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_assignments" ADD CONSTRAINT "FK_744665de79cca9e5d59a28a0ad1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog_items" ADD CONSTRAINT "FK_5981708472164aff2b14e49024c" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_by_location" ADD CONSTRAINT "FK_eb039403817535895c40439fec5" FOREIGN KEY ("catalogItemId") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_by_location" ADD CONSTRAINT "FK_35a43d299f796bbd64c3ffd0b58" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_units" ADD CONSTRAINT "FK_207ba92026ecaf18b2cdaa56005" FOREIGN KEY ("catalogItemId") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_units" ADD CONSTRAINT "FK_5ea2e097876d327f5d186fc6377" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_e324eadbd3cc72c15c27de9ba28" FOREIGN KEY ("catalogItemId") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_e0ccdc14bc299781045945f4ae2" FOREIGN KEY ("assetUnitId") REFERENCES "asset_units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_4bb5e2d1c85b15fe6365ac84b79" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_92bdf735ec66f531841846d5d9e" FOREIGN KEY ("assignedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_e75b2750624340b2c4bfeb5e1e2" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_fc05e172b9d043e42e1a00cc880" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_transactions" ADD CONSTRAINT "FK_98f7c49dfdbead469306db61891" FOREIGN KEY ("assignmentId") REFERENCES "assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_transactions" ADD CONSTRAINT "FK_c349f9fd13ff2561048c30b038a" FOREIGN KEY ("returnedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_transactions" ADD CONSTRAINT "FK_7ff39d247156ab5d2bb1657ef02" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" ADD CONSTRAINT "FK_4d970745eadf189304adbb55c5b" FOREIGN KEY ("catalogItemId") REFERENCES "catalog_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" ADD CONSTRAINT "FK_99457e843c77a047dc5c09c444a" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" ADD CONSTRAINT "FK_b5b5fc38046b507f896b2ba889b" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_history" ADD CONSTRAINT "FK_71366f68da9352e522f8749102b" FOREIGN KEY ("license_id") REFERENCES "licenses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_history" ADD CONSTRAINT "FK_e17e162b408bd34d82f91a0303c" FOREIGN KEY ("performed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "license_history" ADD CONSTRAINT "FK_dc2e0631ae91bcf0425420daa43" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_assignments" ADD CONSTRAINT "FK_bcf2a334e40205c646e0809886e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_assignments" ADD CONSTRAINT "FK_a465dc60ed67f1d1446badc51b8" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_purchases" ADD CONSTRAINT "FK_ab1c8fc51f58d8cd42c00412e87" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD CONSTRAINT "FK_934d5a332b6870c7bb95643ab41" FOREIGN KEY ("category_id") REFERENCES "inventory_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_073259120ddd23357a88f7cd113" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_e9ee5e047ab2db01665b51affe6" FOREIGN KEY ("performed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" ADD CONSTRAINT "FK_7e167af91b810bc3a3b5305fa30" FOREIGN KEY ("assignment_id") REFERENCES "inventory_assignments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" ADD CONSTRAINT "FK_93095f62486b717bac39a63dd51" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" ADD CONSTRAINT "FK_27c1eb883ee4d6afc5ddc98c320" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_audits" ADD CONSTRAINT "FK_329eb1f115d26aafbfb40c9c04a" FOREIGN KEY ("auditor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_audit_details" ADD CONSTRAINT "FK_b25359c63bd33238db2d325f362" FOREIGN KEY ("audit_id") REFERENCES "inventory_audits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_audit_details" ADD CONSTRAINT "FK_39e36b3de2a85a9e7a51193577f" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_events" ADD CONSTRAINT "FK_9e76ea4cc84a0e407c5a3aeb054" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_history" ADD CONSTRAINT "FK_7621be09cced32b245cf6c45230" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_history" ADD CONSTRAINT "FK_c985631fad3ad22e4cb6741f0e8" FOREIGN KEY ("performed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_history" ADD CONSTRAINT "FK_9e16ea8ed7a02c1e5b04de91a6b" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "asset_history" DROP CONSTRAINT "FK_9e16ea8ed7a02c1e5b04de91a6b"`);
        await queryRunner.query(`ALTER TABLE "asset_history" DROP CONSTRAINT "FK_c985631fad3ad22e4cb6741f0e8"`);
        await queryRunner.query(`ALTER TABLE "asset_history" DROP CONSTRAINT "FK_7621be09cced32b245cf6c45230"`);
        await queryRunner.query(`ALTER TABLE "audit_events" DROP CONSTRAINT "FK_9e76ea4cc84a0e407c5a3aeb054"`);
        await queryRunner.query(`ALTER TABLE "inventory_audit_details" DROP CONSTRAINT "FK_39e36b3de2a85a9e7a51193577f"`);
        await queryRunner.query(`ALTER TABLE "inventory_audit_details" DROP CONSTRAINT "FK_b25359c63bd33238db2d325f362"`);
        await queryRunner.query(`ALTER TABLE "inventory_audits" DROP CONSTRAINT "FK_329eb1f115d26aafbfb40c9c04a"`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" DROP CONSTRAINT "FK_27c1eb883ee4d6afc5ddc98c320"`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" DROP CONSTRAINT "FK_93095f62486b717bac39a63dd51"`);
        await queryRunner.query(`ALTER TABLE "inventory_returns" DROP CONSTRAINT "FK_7e167af91b810bc3a3b5305fa30"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_e9ee5e047ab2db01665b51affe6"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_073259120ddd23357a88f7cd113"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP CONSTRAINT "FK_934d5a332b6870c7bb95643ab41"`);
        await queryRunner.query(`ALTER TABLE "inventory_purchases" DROP CONSTRAINT "FK_ab1c8fc51f58d8cd42c00412e87"`);
        await queryRunner.query(`ALTER TABLE "inventory_assignments" DROP CONSTRAINT "FK_a465dc60ed67f1d1446badc51b8"`);
        await queryRunner.query(`ALTER TABLE "inventory_assignments" DROP CONSTRAINT "FK_bcf2a334e40205c646e0809886e"`);
        await queryRunner.query(`ALTER TABLE "license_history" DROP CONSTRAINT "FK_dc2e0631ae91bcf0425420daa43"`);
        await queryRunner.query(`ALTER TABLE "license_history" DROP CONSTRAINT "FK_e17e162b408bd34d82f91a0303c"`);
        await queryRunner.query(`ALTER TABLE "license_history" DROP CONSTRAINT "FK_71366f68da9352e522f8749102b"`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" DROP CONSTRAINT "FK_b5b5fc38046b507f896b2ba889b"`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" DROP CONSTRAINT "FK_99457e843c77a047dc5c09c444a"`);
        await queryRunner.query(`ALTER TABLE "stock_ledger" DROP CONSTRAINT "FK_4d970745eadf189304adbb55c5b"`);
        await queryRunner.query(`ALTER TABLE "return_transactions" DROP CONSTRAINT "FK_7ff39d247156ab5d2bb1657ef02"`);
        await queryRunner.query(`ALTER TABLE "return_transactions" DROP CONSTRAINT "FK_c349f9fd13ff2561048c30b038a"`);
        await queryRunner.query(`ALTER TABLE "return_transactions" DROP CONSTRAINT "FK_98f7c49dfdbead469306db61891"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_fc05e172b9d043e42e1a00cc880"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_e75b2750624340b2c4bfeb5e1e2"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_92bdf735ec66f531841846d5d9e"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_4bb5e2d1c85b15fe6365ac84b79"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_e0ccdc14bc299781045945f4ae2"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_e324eadbd3cc72c15c27de9ba28"`);
        await queryRunner.query(`ALTER TABLE "asset_units" DROP CONSTRAINT "FK_5ea2e097876d327f5d186fc6377"`);
        await queryRunner.query(`ALTER TABLE "asset_units" DROP CONSTRAINT "FK_207ba92026ecaf18b2cdaa56005"`);
        await queryRunner.query(`ALTER TABLE "stock_by_location" DROP CONSTRAINT "FK_35a43d299f796bbd64c3ffd0b58"`);
        await queryRunner.query(`ALTER TABLE "stock_by_location" DROP CONSTRAINT "FK_eb039403817535895c40439fec5"`);
        await queryRunner.query(`ALTER TABLE "catalog_items" DROP CONSTRAINT "FK_5981708472164aff2b14e49024c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "license_assignments" DROP CONSTRAINT "FK_744665de79cca9e5d59a28a0ad1"`);
        await queryRunner.query(`ALTER TABLE "license_assignments" DROP CONSTRAINT "FK_24b5eaffadc6997358d3bd5f379"`);
        await queryRunner.query(`ALTER TABLE "licenses" DROP CONSTRAINT "FK_f2bd0788ec18281811ed136a863"`);
        await queryRunner.query(`ALTER TABLE "licenses" DROP CONSTRAINT "FK_47ae80077d102b313d9572b14a0"`);
        await queryRunner.query(`ALTER TABLE "license_plans" DROP CONSTRAINT "FK_98ef9cd523400a3d25f8652ac5e"`);
        await queryRunner.query(`ALTER TABLE "license_renewals" DROP CONSTRAINT "FK_227c0a412f8eb5bbbe24b84f697"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_6606d89e4be6895f6a4551feaad"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_ec53e5ca409bb03e5f43bf23a27"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_a4d58da8b1bdb73a0946964e6cc"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_37a207d834cdfe6e294616342f7"`);
        await queryRunner.query(`ALTER TABLE "asset_photos" DROP CONSTRAINT "FK_9760c76293e0a181a0a6250b902"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "asset_history"`);
        await queryRunner.query(`DROP TYPE "public"."asset_history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68d908019304f757740bc47a0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_746df228cec6a874b390563e1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e76ea4cc84a0e407c5a3aeb05"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f51b93a1819ea59b9df7d9855"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f58e6602b568fd712285ea2bc"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP TYPE "public"."audit_events_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "inventory_audit_details"`);
        await queryRunner.query(`DROP TABLE "inventory_audits"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_audits_status_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_returns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073259120ddd23357a88f7cd11"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TABLE "inventory_purchases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcf2a334e40205c646e0809886"`);
        await queryRunner.query(`DROP TABLE "inventory_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_assignments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_assignments_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_categories"`);
        await queryRunner.query(`DROP TABLE "license_history"`);
        await queryRunner.query(`DROP TYPE "public"."license_history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a67d66a61b50be403324772469"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52b319a89e98ef1a1942c94435"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77bb476a348b79a1855957b417"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7806525fee4483e4e10cca783"`);
        await queryRunner.query(`DROP TABLE "stock_ledger"`);
        await queryRunner.query(`DROP TYPE "public"."stock_ledger_reason_enum"`);
        await queryRunner.query(`DROP TABLE "lookups"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98f7c49dfdbead469306db6189"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b59291df6f8917de86d4d44eff"`);
        await queryRunner.query(`DROP TABLE "return_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."return_transactions_conditiononreturn_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4b937c5c857e8c50ef7f292f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e324eadbd3cc72c15c27de9ba2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0ccdc14bc299781045945f4ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d17420638d8d432b3a20c0ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce6063ba9705d8ce937dfee002"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8681da666ad9699d568b3e9106"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9956bc6c072603486133d691c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32f5a46a46d9f7e25f68dca948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d387d47199986aa3f399295932"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17a33a486dca5b890f01dde69"`);
        await queryRunner.query(`DROP TABLE "asset_units"`);
        await queryRunner.query(`DROP TYPE "public"."asset_units_condition_enum"`);
        await queryRunner.query(`DROP TYPE "public"."asset_units_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb039403817535895c40439fec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a43d299f796bbd64c3ffd0b5"`);
        await queryRunner.query(`DROP TABLE "stock_by_location"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_227023051ab1fedef7a3b6c7e2"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d43e77f403dce4074eb0f0798"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a3bd6068277aef05f19015871"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f764d91232b2eb16a79aeae76"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf702b2d6db3ff835efd6f11e2"`);
        await queryRunner.query(`DROP TABLE "catalog_items"`);
        await queryRunner.query(`DROP TYPE "public"."catalog_items_trackmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."catalog_items_returnpolicy_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "license_assignments"`);
        await queryRunner.query(`DROP TABLE "licenses"`);
        await queryRunner.query(`DROP TABLE "license_plans"`);
        await queryRunner.query(`DROP TABLE "license_renewals"`);
        await queryRunner.query(`DROP TABLE "assets"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "asset_photos"`);
        await queryRunner.query(`DROP TYPE "public"."asset_photos_condition_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52ac39dd8a28730c63aeb428c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab673f0e63eac966762155508e"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
    }

}
