import { Repository, EntityManager } from 'typeorm';
import { Asset } from '../entities/asset.entity';
import { AssetHistory } from '../entities/asset-history.entity';
import { AssetPhoto } from '../entities/asset-photo.entity';
import { User } from '../entities/user.entity';
import { Category } from '../entities/category.entity';
export declare class AssetsService {
    private assetsRepository;
    private historyRepository;
    private photoRepository;
    private usersRepository;
    private categoryRepository;
    constructor(assetsRepository: Repository<Asset>, historyRepository: Repository<AssetHistory>, photoRepository: Repository<AssetPhoto>, usersRepository: Repository<User>, categoryRepository: Repository<Category>);
    private logAction;
    findAll(): Promise<Asset[]>;
    findOne(id: number): Promise<Asset>;
    create(data: any, userId?: number, manager?: EntityManager): Promise<Asset>;
    update(id: number, data: any, userId?: number): Promise<Asset>;
    deploy(id: number, data: any, performedBy?: number): Promise<Asset>;
    undeploy(id: number, performedBy?: number): Promise<Asset>;
    scheduleMaintenance(id: number, data: any, performedBy?: number): Promise<Asset>;
    completeMaintenance(id: number, performedBy?: number): Promise<Asset>;
    calculateDepreciation(id: number, performedBy?: number): Promise<Asset>;
    dispose(id: number, data: any, performedBy?: number): Promise<Asset>;
    getHistory(id: number): Promise<AssetHistory[]>;
    delete(id: number): Promise<void>;
    getStatistics(): Promise<any>;
    uploadPhotos(assetId: number, files: Express.Multer.File[], body: any): Promise<any[]>;
    getPhotos(assetId: number): Promise<any[]>;
    deletePhoto(assetId: number, photoId: number): Promise<void>;
}
